# Generated by Django 3.2.3 on 2021-07-07 12:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20210707_1333")]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", api.models.CallerUserManager())]
        ),
        migrations.AlterField(
            model_name="contact", name="number", field=models.PositiveBigIntegerField()
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.PositiveBigIntegerField(
                help_text="unique number for a user to register", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
